<?php

namespace Blog\BlogBundle\Entity;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function countPost()
    {
        $qb = $this->createQueryBuilder('a');
        $query = $qb->select('COUNT(a.id)');
        $count = $query->getQuery()->getSingleScalarResult();

        return $count;
    }

    public function countByCat(Cat $cat)
    {
        $qb = $this->createQueryBuilder('a');
        $query = $qb->select('COUNT(a.id)')
            ->where('a.cat = :cat')
            ->setParameter('cat', $cat);
        $count = $query->getQuery()->getSingleScalarResult();

        return $count;
    }
}
